## This notebook is designed to both work through a solution *and* demonstrate a systematic way to approach a coding challenge, including tests, validating on small data sets, and trying different approaches.

In [50]:
import numpy as np

In [51]:
names = ['jason', 'Rajasheker', 'Sudhukar', 'Billy','Bobby']

In [52]:
names

['jason', 'Rajasheker', 'Sudhukar', 'Billy', 'Bobby']

In [53]:
#Let's try some subsetting / indexing experiments

In [54]:
names[-1]  #Since this is a list, it will pick the last item in the list, not the last letter of each item

'Bobby'

In [55]:
names[-1][-1] #However, I can also subset a subset, so this could be a way to isolate the last character

'y'

In [56]:
#Now that I have figured out the logic to isolate the last character in each name, how do I do this
#programmatically - say, if I had a list of 1000 names? Maybe try a simple for loop approach to test the logic

In [57]:
for name in names:
    eval = name[-1]
    print(eval) 

n
r
r
y
y


In [58]:
#Note that I'm testing the logic on a much smaller subset of data. This allows me to make sure I'm getting
#the outputs I expect and can understand what I'm seeing. Also note, I'm not actually storing any values or
#returning any values at this point. This is a logic test. I'm not writing the function yet.

In [59]:
#From here I could create a number of ways to evaluate the problem. I could write a bunch of if statements
#to check if the letters I'm pulling out are in the list of characters I care about, or I could use
#the NumPy isin function to do the work for me. One way to approach this might be:

In [60]:
#Start by creating an empty list to store the characters to be evaluated.
lastchars = []

#Next, let's implement the logic that I know works and fill out the list
for name in names:
    eval = name[-1]
    #print(eval) - commented out because I no longer need to validate this works as expected.
    lastchars.append(eval)
    #Let's print this at each step to make sure it's building like we expect
    print(lastchars)

['n']
['n', 'r']
['n', 'r', 'r']
['n', 'r', 'r', 'y']
['n', 'r', 'r', 'y', 'y']


In [61]:
#And now let's make sure we've stored this properly outside of the for loop
lastchars

['n', 'r', 'r', 'y', 'y']

In [62]:
#OK, cool. Now we can either create another loop to evaluate each character, or utilize 
#NumPy's isin function. To simplify, let's create the list to evaluate before we do this.

In [63]:
vowels = ['a', 'e', 'i','o','u','y']

In [64]:
#And now, following the documentation, let's see what we get (again, not storing anything yet, 
#just looking at outputs)

In [65]:
np.isin(lastchars, vowels)

array([False, False, False,  True,  True])

In [66]:
#This appears to be working properly now. 

In [71]:
#Let's try the other approach, using the NumPy char.endswith function to test for the letter 'y'
#without having to first pull out the last letter from each name.
np.char.endswith(names, 'y')

array([False, False, False,  True,  True])

In [72]:
#OK, this worked and seems simpler. However, there's a catch.

np.char.endswith(names, vowels)

ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [73]:
#Now, instead of having to pull out the last set of characters and run them through a list to check, 
#we have to try every name in our names list separately for each vowel.

In [74]:
#Which approach is better, do you think, and why do you think that?

In [81]:
#One last tip - what if I wanted to return the opposite?

In [77]:
np.logical_not(np.char.endswith(names, 'y'))

array([ True,  True,  True, False, False])

In [80]:
np.logical_not(np.isin(lastchars, vowels))

array([ True,  True,  True, False, False])

### By Jason Eden