# Fun with Matrices

In [1]:
import numpy as np

## Element-wise multiplication

### Let's create a couple of matrices with the same shape

In [5]:
matrix1 = np.random.rand(3, 5)
print(matrix1)

[[0.48648143 0.31265133 0.54197392 0.313235   0.21338059]
 [0.69665406 0.0722885  0.301989   0.46795963 0.89079005]
 [0.99599151 0.50817115 0.56234987 0.41278708 0.42643855]]


In [6]:
matrix2 = np.random.rand(3, 5)
print(matrix2)

[[0.86192738 0.24819291 0.88426159 0.82033332 0.90285396]
 [0.41193118 0.75909385 0.47265607 0.5540956  0.90340876]
 [0.99451903 0.67467346 0.64576588 0.71761088 0.17557481]]


In [15]:
FirstProduct = np.multiply(matrix1, matrix2)
print(FirstProduct)

[[0.41931167 0.07759784 0.47924672 0.25695711 0.19265151]
 [0.28697352 0.05487375 0.14273693 0.25929437 0.80474754]
 [0.99053251 0.34284959 0.36314636 0.2962205  0.07487187]]


#### Note - you can use "*" instead of np.multiply - identical results

In [23]:
FirstProductAlt = matrix1 * matrix2
print(FirstProductAlt)

[[0.41931167 0.07759784 0.47924672 0.25695711 0.19265151]
 [0.28697352 0.05487375 0.14273693 0.25929437 0.80474754]
 [0.99053251 0.34284959 0.36314636 0.2962205  0.07487187]]


### What's happened? Every element in the first matrix has been multiplied with the corresponding element in the second matrix.

### Look at the first value in the first matrix and separate matrix (and practice our subsetting at the same time):

#### We want the first value in the first row, so we can start by simply subsetting the first row of data from matrix1.

In [10]:
m1FirstRow = matrix1[0]
print(m1FirstRow)

[0.48648143 0.31265133 0.54197392 0.313235   0.21338059]


#### Next, we can subset this row of data and just grab the first value / column:

In [12]:
m1FirstRowFirstColumn = m1FirstRow[0]
print(m1FirstRowFirstColumn)

0.4864814346549454


#### Note: We did not have to do this in two steps, as you can subset a subset like so:

In [13]:
m1FirstValue = matrix1[0][0]
print(m1FirstValue)

0.4864814346549454


#### So now we know the easy way to grab the value we want, repeat the operation for the second matrix:

In [17]:
m2FirstValue = matrix2[0][0]
print(m2FirstValue)

0.8619273795284207


#### Now, to confirm that we have indeed performed an element-wise multiplication, check the product of the first value in each matrix vs. the first value of the resulting matrix when we used np.multiply:

In [18]:
m1FirstValue * m2FirstValue

0.4193116681613637

In [19]:
FirstProduct[0][0]

0.4193116681613637

#### We have a match!

## What happens if we try to multiply matrices that do not have the same shape?

In [21]:
matrix3 = np.random.rand(6, 3)
print(matrix3)

[[0.30336823 0.98736003 0.28804117]
 [0.83649174 0.76903331 0.66633132]
 [0.17058183 0.23673478 0.3554308 ]
 [0.28499783 0.59626952 0.09996508]
 [0.10223562 0.06169455 0.67273933]
 [0.3024988  0.43814816 0.52886833]]


In [22]:
np.multiply(matrix1, matrix3)

ValueError: operands could not be broadcast together with shapes (3,5) (6,3) 

In [24]:
matrix1 * matrix 3

SyntaxError: invalid syntax (580078671.py, line 1)

#### You cannot perform this operation because there is not a corresponding value in matrix1 for every value in matrix3.

## Inner / Dot Product

### Dot products can be calculated as long as their "inner" values match. For example, matrix1 and matrix2 both have shapes of 3, 5

In [25]:
np.shape(matrix1)

(3, 5)

In [26]:
np.shape(matrix2)

(3, 5)

## Can we calculate a dot product of these two matrices as-is?

In [27]:
np.dot(matrix1, matrix2)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

## Nope! The inner values for the matrices are the second shape value of the first matrix and the first shape value of the second matrix. Those values are 5 and 3, respectively, and thus we cannot perform an inner product calculation.

### In order to get this to work, we need to change the shape of one of the matrices. One way to do this is to transpose:

In [28]:
print(matrix2)

[[0.86192738 0.24819291 0.88426159 0.82033332 0.90285396]
 [0.41193118 0.75909385 0.47265607 0.5540956  0.90340876]
 [0.99451903 0.67467346 0.64576588 0.71761088 0.17557481]]


In [29]:
print(np.transpose(matrix2))

[[0.86192738 0.41193118 0.99451903]
 [0.24819291 0.75909385 0.67467346]
 [0.88426159 0.47265607 0.64576588]
 [0.82033332 0.5540956  0.71761088]
 [0.90285396 0.90340876 0.17557481]]


### Transposing a matrix makes its rows into columns and columns into rows. Can be done with np.transpose (as shown above) or by using ".T" at the end of the matrix (as shown below).

In [30]:
print(matrix2.T)

[[0.86192738 0.41193118 0.99451903]
 [0.24819291 0.75909385 0.67467346]
 [0.88426159 0.47265607 0.64576588]
 [0.82033332 0.5540956  0.71761088]
 [0.90285396 0.90340876 0.17557481]]


### Thus, to be able to do an inner product with our two matrices, we need to transpose one of them:

In [32]:
np.dot(matrix1, matrix2.T)

array([[1.42576485, 1.06022786, 1.30698596],
       [2.07358018, 1.54862612, 1.42883425],
       [2.20549595, 1.67579945, 2.06762082]])

#### You can also use "@" instead of np.dot

In [33]:
matrix1 @ matrix2.T

array([[1.42576485, 1.06022786, 1.30698596],
       [2.07358018, 1.54862612, 1.42883425],
       [2.20549595, 1.67579945, 2.06762082]])

### Another option is to use np.inner, which automatically transposes the second matrix for you.

In [36]:
np.inner(matrix1, matrix2)

array([[1.42576485, 1.06022786, 1.30698596],
       [2.07358018, 1.54862612, 1.42883425],
       [2.20549595, 1.67579945, 2.06762082]])

### ...and thus errors out if you transpose it yourself.

In [37]:
np.inner(matrix1, matrix2.T)

ValueError: shapes (3,5) and (3,5) not aligned: 5 (dim 1) != 3 (dim 0)

### Note that **only** the inner shape values have to match. Let's go back to our matrices that could not be multiplied using element-wise multiplication and check their shapes

In [41]:
matrix1.shape

(3, 5)

In [42]:
matrix3.shape

(6, 3)

### Can we perform an inner product calculation?

In [43]:
matrix3 @ matrix1

array([[1.12231794, 0.31259747, 0.62456945, 0.67596985, 1.06709524],
       [1.60634821, 0.65573287, 1.06030764, 0.89694799, 1.14768768],
       [0.6019132 , 0.25106552, 0.36381867, 0.31093176, 0.39884923],
       [0.6536041 , 0.18300775, 0.39074358, 0.40956565, 0.63459292],
       [0.76275815, 0.37829063, 0.45235499, 0.33859244, 0.36365397],
       [0.9791461 , 0.39500535, 0.59367142, 0.51809887, 0.68037524]])

### Success! But does the order matter?

In [44]:
matrix1 @ matrix3

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 6 is different from 5)

### Yes, order matters. Changing the order changed the "inner" shape values, and thus this operation cannot be performed.

## Operations Within a Matrix

## What if we want to sum all of the values in matrix 1?

In [45]:
np.sum(matrix1)

7.203141667976959

## What if we want to sum all of the **columns** for matrix1? 

### Answer - Sum across axis 0

In [49]:
matrix1

array([[0.48648143, 0.31265133, 0.54197392, 0.313235  , 0.21338059],
       [0.69665406, 0.0722885 , 0.301989  , 0.46795963, 0.89079005],
       [0.99599151, 0.50817115, 0.56234987, 0.41278708, 0.42643855]])

In [50]:
np.sum(matrix1, axis = 0)

array([2.179127  , 0.89311098, 1.40631279, 1.19398171, 1.53060919])

#### Note I have five columns and I get five results in return.

## What if we want to sum each of the rows instead? 

### Sum across axis 1

In [51]:
np.sum(matrix1, axis = 1)

array([1.86772227, 2.42968124, 2.90573816])

#### Note I have three rows and I get three results in return.

## Another common operation: products within a matrix

In [52]:
np.prod(matrix1)

1.7500326994134286e-06

In [53]:
np.prod(matrix1, axis = 0)

array([0.33755075, 0.01148522, 0.0920399 , 0.06050688, 0.08105629])

In [54]:
np.prod(matrix1, axis = 1)

array([0.00550973, 0.00633959, 0.05010197])