# Fun with Indexing and Slicing

In [1]:
import numpy as np

## Create a range of values from 0 to 9

In [4]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


### Create another array of the same size, but this time starting at 10

In [8]:
array2 = np.arange(10,20)
print(array2)

[10 11 12 13 14 15 16 17 18 19]


### Note that the default arange function assumes you want to start at 0. However, if you supply two values separated by a comma, it starts at the first value and goes up to (but does not include the last value). Thus, we could have written array1 as:

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ok, so for our third array, lets create one that starts at 1, stops before 30, and counts by 3's

In [12]:
array3 = np.arange(1, 30, 3)
print(array3)

[ 1  4  7 10 13 16 19 22 25 28]


#### All three arrays have the same shape (10,)

In [15]:
array3.shape

(10,)

## Indexing

## Let's grab values out of our arrays

### To grab the fourth value out of an array, specify index 3 (because we start with 0...)

In [16]:
array1[3]

3

In [17]:
array2[3]

13

In [18]:
array3[3]

10

## Let's grab a range of values out of our arrays

### Grab the first 3 values

In [19]:
array1[:3]

array([0, 1, 2])

#### Note: similar to when we created a range using arange, the second number specifies the stop point but that point is not included in the resulting output. Thus, [:3] results in the values for index positions 0, 1, and 2, but not 3.

In [21]:
array1[0:3]

array([0, 1, 2])

### Note that we could have specified the starting point as 0 instead of leaving it empty and gotten the same result. We can also specify a different starting point:

In [22]:
array1[1:3]

array([1, 2])

In [23]:
array1[2:9]

array([2, 3, 4, 5, 6, 7, 8])

### We can specify a third value to grab every nth value, instead of all values between the first and second numbers given.

In [24]:
array1[2:9:2]

array([2, 4, 6, 8])

In [25]:
array1[2:9:3]

array([2, 5, 8])

## Note that the logic for arange and for indexing and slicing is the same - first number provides the starting point, second number provides the end (but do not include) point, and the third number provides the interval.

### In indexing and slicing, if no numbers are provided between the colons, the first number is assumed to be 0, the last number is assumed to be the final available value, and the interval is assumed to be 1.

In [26]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array1[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array1[0:10:1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Reversing order and negative numbers

### You can specify start and stop points in reverse order if you specify a negative interval

In [33]:
#Return all values in reverse order
array1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [34]:
#Start at index position 8 and stop (but do not include) 2
array1[8:2:-1]

array([8, 7, 6, 5, 4, 3])

In [35]:
#Start at index position 8 and stop (but do not include) 2, count by 2's
array1[8:2:-2]

array([8, 6, 4])

### You can specify index position based on reverse order by using negative numbers as well

In [36]:
array1[-1]

9

In [37]:
array1[-4]

6

## Matrix Indexing and Slicing

### Let's turn our three arrays into a 3x10 matrix

In [55]:
matrix = np.stack((array1, array2, array3))
print(matrix)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [ 1  4  7 10 13 16 19 22 25 28]]


In [56]:
matrix.shape

(3, 10)

### Now that we have two axes that we can navigate, let's see what happens when we try a simple index - say, index position 1

In [57]:
matrix[1]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Note that a single index position now returns and entire row instead of a single value. If we want to just get a single value - say the first one - out of this row, we can subset the subset we created.

In [58]:
matrix[1][0]

10

### Alternatively, we could have specified both values in the original subset, separated by a comma

In [59]:
matrix[1,0]

10

## More examples

In [66]:
matrix #Keeping the visual in mind

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28]])

In [63]:
matrix[1:] #Returns rows starting with 1 to the end of the matrix

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28]])

In [62]:
matrix[1:,0] #Returns the 0th index position of the rows returned prior to the comma

array([10,  1])

In [67]:
matrix[:2,2] #Returns rows from 0 to 1, and index position 2 in those rows

array([ 2, 12])

In [69]:
matrix[:,2:5] #Returns all rows, then index positions 2 through 4 in those rows

array([[ 2,  3,  4],
       [12, 13, 14],
       [ 7, 10, 13]])

In [71]:
matrix[::2] #Returns all rows at every 2nd interval

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28]])

In [72]:
matrix[::-2] #Same but in reverse

array([[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [74]:
matrix[::2, 9:1:-3] #Returns all rows at every 2nd interval, the positions 9 through 2 at every third interval

array([[ 9,  6,  3],
       [28, 19, 10]])

In [76]:
matrix[1,5]

15