In [1]:
import numpy as np

In [54]:
x = np.array(([1,4,1,1],[2,8,2,3]))

In [64]:
vals, counts = np.unique(x[1], return_counts = True) 

In [65]:
vals

array([2, 3, 8])

In [66]:
counts

array([2, 1, 1])

In [67]:
index = np.argmax(counts)

In [68]:
index

0

In [69]:
pred = vals[index]

In [70]:
pred

2

In [89]:
# https://www.delftstack.com/howto/numpy/python-numpy-mode/

In [76]:
def classify(inputdata):
    n, d = inputdata.shape
    preds = np.zeros(n)
    for i in range(n):
        vals,counts = np.unique(x[i], return_counts = True)
        index = np.argmax(counts)
        preds[i] = vals[index]
    return preds

In [77]:
classify(x)

array([1., 2.])

In [78]:
def npmode(inputrow):
    vals,counts = np.unique(inputrow, return_counts = True)
    index = np.argmax(counts)
    prediction = vals[index]
    return prediction

In [79]:
x

array([[1, 4, 1, 1],
       [2, 8, 2, 3]])

In [81]:
npmode(x[1])

2

In [85]:
def classify2(inputdata):
    n, d = inputdata.shape
    preds = np.zeros(n)
    for i in range(n):
        preds[i] = npmode(inputdata[i])
    return preds  

In [86]:
classify2(x)

array([1., 2.])