In [1]:
import numpy as np

In [38]:
vowels=np.array(['a','e','i','o','u','y'])

In [39]:
vowels

array(['a', 'e', 'i', 'o', 'u', 'y'], dtype='<U1')

In [40]:
names = ['jason','syed']

In [48]:
#This will evaluate multiple names, but only one character at a time
np.char.endswith(names, 'n')

array([ True, False])

In [49]:
np.char.endswith(names, 'a')

array([False, False])

In [43]:
lastchar = [x[-1] for x in names]

In [44]:
np.isin(lastchar,vowels)

array([False, False])

In [45]:
#do a postivie test make sure eval is working

In [46]:
otherletters = np.array(['n','z','g'])

In [47]:
np.isin(lastchar,otherletters)

array([ True, False])