In [35]:
import numpy as np

In [59]:
numobservations = 20
numdimensions = 4

In [60]:
xs = np.random.rand(numobservations,numdimensions)

In [61]:
xs

array([[0.23700043, 0.83655424, 0.87870756, 0.52306209],
       [0.59535725, 0.12074825, 0.2014483 , 0.85671084],
       [0.58351209, 0.00963455, 0.94550828, 0.65788458],
       [0.92014546, 0.14849856, 0.39156441, 0.04416041],
       [0.29510043, 0.29093829, 0.62904535, 0.84283234],
       [0.23778787, 0.5449531 , 0.14541744, 0.91307655],
       [0.07663442, 0.58355686, 0.86343709, 0.21267774],
       [0.85282284, 0.92338082, 0.65646076, 0.15859554],
       [0.29418088, 0.75268536, 0.49495968, 0.18792869],
       [0.9169381 , 0.46995676, 0.65843668, 0.82628184],
       [0.51381535, 0.54301522, 0.32963226, 0.57563331],
       [0.20303606, 0.53832573, 0.76599792, 0.06602682],
       [0.77241312, 0.92701537, 0.2930222 , 0.55454775],
       [0.8275125 , 0.84650479, 0.31556974, 0.8427153 ],
       [0.68238774, 0.84835075, 0.53755998, 0.38627889],
       [0.68695793, 0.92085283, 0.8484584 , 0.6313438 ],
       [0.59523535, 0.15471884, 0.55480036, 0.22314389],
       [0.62774785, 0.0184144 ,

In [62]:
b_adjust = np.ones(xs.shape[0])

In [63]:
b_adjust

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [64]:
b_adjust = b_adjust.reshape((xs.shape[0],1))

In [65]:
b_adjust

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [66]:
xs_edited = np.hstack((xs, b_adjust))

In [67]:
xs_edited

array([[0.23700043, 0.83655424, 0.87870756, 0.52306209, 1.        ],
       [0.59535725, 0.12074825, 0.2014483 , 0.85671084, 1.        ],
       [0.58351209, 0.00963455, 0.94550828, 0.65788458, 1.        ],
       [0.92014546, 0.14849856, 0.39156441, 0.04416041, 1.        ],
       [0.29510043, 0.29093829, 0.62904535, 0.84283234, 1.        ],
       [0.23778787, 0.5449531 , 0.14541744, 0.91307655, 1.        ],
       [0.07663442, 0.58355686, 0.86343709, 0.21267774, 1.        ],
       [0.85282284, 0.92338082, 0.65646076, 0.15859554, 1.        ],
       [0.29418088, 0.75268536, 0.49495968, 0.18792869, 1.        ],
       [0.9169381 , 0.46995676, 0.65843668, 0.82628184, 1.        ],
       [0.51381535, 0.54301522, 0.32963226, 0.57563331, 1.        ],
       [0.20303606, 0.53832573, 0.76599792, 0.06602682, 1.        ],
       [0.77241312, 0.92701537, 0.2930222 , 0.55454775, 1.        ],
       [0.8275125 , 0.84650479, 0.31556974, 0.8427153 , 1.        ],
       [0.68238774, 0.84835075, 0.

In [68]:
ys_starter = np.random.randint(0, 2, xs.shape[0])

In [69]:
ys_starter

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0])

In [70]:
ys_starter[ys_starter == 0] = -1

In [71]:
ys = ys_starter

In [72]:
ys

array([ 1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,
        1, -1, -1])

In [73]:
initial_w = np.zeros(numdimensions)

In [74]:
initial_b = 0.0

In [75]:
new_w = np.zeros(numdimensions+1)

In [76]:
new_w

array([0., 0., 0., 0., 0.])

In [78]:
#Our first perceptron iteration

In [94]:
randomindexvalue = 11

In [98]:
#evaluate if our current weight vector returns the right sign with this observation
ys[randomindexvalue]*(new_w @ xs_edited[randomindexvalue]) > 0

False

In [99]:
ys[randomindexvalue]*(new_w @ xs_edited[randomindexvalue])

-0.0

In [97]:
#If it evaluates true, this point is correctly classified 
#(the sign of ys = sign of new_w @ xs_edited for that observation)
#If false, then we need to update new_w
#The first one will always return false because it will be 0