# A quick example of how to index instead of looping in order to dramatically speed up code.

In [1]:
import numpy as np

### Let's generate a 4 x 4 array of data

In [2]:
data = np.array([[8,4,2,1],[3,3,5,3],[9,2,1,5],[4,1,1,7]])

In [3]:
data

array([[8, 4, 2, 1],
       [3, 3, 5, 3],
       [9, 2, 1, 5],
       [4, 1, 1, 7]])

### Now let's give each observation a label of 0 or 1

In [4]:
labels = np.array([1,0,1,0])

In [5]:
labels

array([1, 0, 1, 0])

### First demonstration: How to subset the data using the labels, using the "==" operator

Can use other logical operators as well.

In [6]:
labelguide = data[labels==1]

In [7]:
labelguide

array([[8, 4, 2, 1],
       [9, 2, 1, 5]])

### Note that this only printed the observations that matched the position where labels was set to 1.

### Now generate a vector that we will later populate with some data based on our original data

In [8]:
datastuff = np.zeros(4)

### Let's say we want to use np.sum on all of the observations that were labeled with a 1. Here's how you'd do that.

In [9]:
datastuff[labels==1] = np.sum(data[labels==1], axis = 1)

In [10]:
datastuff

array([15.,  0., 17.,  0.])

### Note that only the values we want were populated, the others were left as zeroes. Now, lets' say we want to use np.prod on all of the observations that were labeled as zero. Here's how you'd do that.

In [11]:
datastuff[labels==0] = np.prod(data[labels==0], axis = 1)

In [12]:
datastuff

array([ 15., 135.,  17.,  28.])

### We have now demonstrated how to subset a data matrix by its labels, and then further demonstrated that we can now populate an output based on different computations performed on data based on the label and have the results show up in the right place in our output.

In [11]:
assert False, "DO NOT REMOVE THIS LINE"

AssertionError: DO NOT REMOVE THIS LINE

---

In [2]:
%%bash
git pull
git add SliceVsLoop.ipynb
git commit -a -m "Slice vs Loop Example"
git push

Already up to date.
[main 438f296] Slice vs Loop Example
 1 file changed, 24 insertions(+), 7 deletions(-)


To github.com:jasondeden/GCP-Jupyter.git
   b5fdb8d..438f296  main -> main
