# Vector Math Basics

In [1]:
import numpy as np

## Start by creating a simple NumPy array

In [2]:
vecA = np.array([1,2])

In [3]:
vecA

array([1, 2])

## Multiply an array with a scalar = every array element is multiplied by the same number

In [4]:
vecA*2

array([2, 4])

### The "*" is equivalent to np.multiply()

In [5]:
np.multiply(vecA, 2)

array([2, 4])

## Create another simple array with the same dimensions

In [8]:
vecB = np.array([2, 1])

In [9]:
vecB

array([2, 1])

In [10]:
vecA.shape

(2,)

In [11]:
vecB.shape

(2,)

## Since the two objects have the same shape, we can perform element-wise addition and subtraction

### Each array element is added to / subtracted from its counterpart in the other array

In [7]:
vecA + vecB

array([3, 3])

### Both "+" and "-" have NumPy equivalents

In [12]:
np.add(vecA, vecB)

array([3, 3])

In [8]:
vecA - vecB

array([-1,  1])

In [13]:
np.subtract(vecA, vecB)

array([-1,  1])

## Create a couple of matrices with different shapes

In [15]:
vecC = np.array([[1, 2],[1,2]])

In [16]:
vecC

array([[1, 2],
       [1, 2]])

In [17]:
vecC.shape

(2, 2)

In [18]:
vecD = np.array([[2, 4],[2, 4],[2, 4]])

In [19]:
vecD.shape

(3, 2)

## For element-wise operations, if shapes to not match, an error is returned

In [20]:
vecC + vecD

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [21]:
vecC * vecD

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

## Inner (dot) products do not require the same shape, however the inner values of the matrices must match

In [23]:
vecD @ vecC

array([[ 6, 12],
       [ 6, 12],
       [ 6, 12]])

### The "@" is equivalent to np.dot() and np.matmul for matrices()

In [24]:
np.dot(vecD, vecC)

array([[ 6, 12],
       [ 6, 12],
       [ 6, 12]])

In [25]:
np.matmul(vecD, vecC)

array([[ 6, 12],
       [ 6, 12],
       [ 6, 12]])

## Unlike element-wise multiplication, however, the order of the matrices matters. 

In [18]:
np.dot(vecC, vecD)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

### Some sample test outputs using random values and different notations, plus print statements

In [28]:
a = np.random.rand(2,3,3)
b = np.random.rand(2,3,3)
c = (a@b)
d = np.dot(a,b)
e = np.matmul(a,b)
print(c,c.shape)
print(d,d.shape)
print(e,e.shape)

[[[0.72284301 0.78819667 1.75736585]
  [0.29943639 0.2256965  0.48559498]
  [1.1018824  0.895632   1.73699127]]

 [[0.6439384  0.4157148  0.88052342]
  [0.65465794 0.13490045 0.26513794]
  [0.91607222 0.43324144 0.51869675]]] (2, 3, 3)
[[[[0.72284301 0.78819667 1.75736585]
   [0.92133939 0.44757833 0.47996982]]

  [[0.29943639 0.2256965  0.48559498]
   [0.22951571 0.1585242  0.25172468]]

  [[1.1018824  0.895632   1.73699127]
   [0.75662856 0.58597782 0.84686385]]]


 [[[0.83965757 0.43712184 1.21894514]
   [0.6439384  0.4157148  0.88052342]]

  [[0.17441839 0.14064959 0.86718467]
   [0.65465794 0.13490045 0.26513794]]

  [[0.71016714 0.72447874 1.70214576]
   [0.91607222 0.43324144 0.51869675]]]] (2, 3, 2, 3)
[[[0.72284301 0.78819667 1.75736585]
  [0.29943639 0.2256965  0.48559498]
  [1.1018824  0.895632   1.73699127]]

 [[0.6439384  0.4157148  0.88052342]
  [0.65465794 0.13490045 0.26513794]
  [0.91607222 0.43324144 0.51869675]]] (2, 3, 3)


In [25]:
e = np.matmul(a,b)
print(e, e.shape)

[[[0.40225736 0.36111255 0.19669152]
  [1.09558214 1.51638612 0.24240802]
  [0.92671046 0.96806502 0.43087234]]

 [[0.86517875 0.70266539 1.04754084]
  [0.58616427 0.80991035 0.71268113]
  [0.33296999 0.77262947 0.37741854]]] (2, 3, 3)


## Arrays can contain more than just numbers

In [26]:
diffarray = np.array([1, "cheese", 24.2])

In [27]:
diffarray

array(['1', 'cheese', '24.2'], dtype='<U32')

## If an array contains a string, all elements are assumed to be strings. This can lead to some confusing outputs. For example, if I try to add the first array element "1" to another number, an error is returned.

In [35]:
diffarray[0]

'1'

In [29]:
diffarray[0] + 2

TypeError: can only concatenate str (not "int") to str

### However, if I try the same thing, but convert the number to string, Python is able to figure out what I'm trying to do and produce the correct output.

In [30]:
diffarray[0] + "2"

'12'